/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_B0_09 (coord F14), LED */
/* Routed pin properties */
#define BOARD_INITPINS_LED_PERIPHERAL                                      GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_LED_SIGNAL                                        gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED_CHANNEL                                            9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_GPIO                                            GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GPIO_PIN                                           9U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED_GPIO_PIN_MASK                              (1U << 9U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LED_PORT                                            GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LED_PIN                                                9U   /*!< PORT pin number */
#define BOARD_INITPINS_LED_PIN_MASK                                   (1U << 9U)   /*!< PORT pin mask */

/* WAKEUP (coord L6), SW3 */
/* Routed pin properties */
#define BOARD_INITPINS_SW3_PERIPHERAL                                      GPIO5   /*!< Peripheral name */
#define BOARD_INITPINS_SW3_SIGNAL                                        gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SW3_CHANNEL                                            0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW3_GPIO                                            GPIO5   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SW3_GPIO_PIN                                           0U   /*!< GPIO pin number */
#define BOARD_INITPINS_SW3_GPIO_PIN_MASK                              (1U << 0U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_SW3_PORT                                            GPIO5   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_SW3_PIN                                                0U   /*!< PORT pin number */
#define BOARD_INITPINS_SW3_PIN_MASK                                   (1U << 0U)   /*!< PORT pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
